/* Replace with your SQL commands */
ALTER TABLE movies 
ADD PRIMARY KEY (id);

ALTER TABLE movies 
ALTER COLUMN id ADD GENERATED AlWAYS AS IDENTITY (START WITH 101);

ALTER TABLE users 
ADD PRIMARY KEY (id);

ALTER TABLE users 
ALTER COLUMN id ADD GENERATED AlWAYS AS IDENTITY (START WITH 101);